function myfunc(){
    try {
        console.log("code runs successful !!");
        
    } catch (error) {
        console.log("this is an error !!!");
    }
}
myfunc()


